In [3]:
import requests
import pandas as pd

### FourSquare App

In [37]:
#source: https://developer.foursquare.com/docs/build-with-foursquare/categories/
#location id for coffee shop
Coffee_LocationId = '4bf58dd8d48988d1e0931735'

#location id for food
Food_LocationId = '4d4b7105d754a06374d81259'

#location id for diner
Diner_LocationId = '4bf58dd8d48988d147941735'



LocationId_List = [Coffee_LocationId, Food_LocationId, Diner_LocationId]

In [156]:
#client id and client secret from foursquare app
CLIENT_ID = 'JBCSBMLHOHPQ5JP3X223IBJJ2OA2JZCFTPHPOSE5WQXSFXIZ'
CLIENT_SECRET = 'RGBZ3AKMC5DSZNFXT1V3IG25OTUK5FLB3FB2GKQEHIWXR1WF'

# limit of number of venues returned by Foursquare API
LIMIT = 100 
radius = 2000

VERSION = '20210830'

neighborhood_latitude, neighborhood_longitude = 3.208959774004187, 101.66897769780032

url = 'https://api.foursquare.com/v2/venues/explore?&client_id={}&client_secret={}&v={}&ll={},{}&radius={}&limit={}'.format(
    CLIENT_ID, 
    CLIENT_SECRET, 
    VERSION,
    neighborhood_latitude, 
    neighborhood_longitude, 
    radius, 
    LIMIT)

results = requests.get(url).json()

searchResults = results['response']['groups'][0]['items']

venues_list = []
venues_list.append([(
                v['venue']['name'], 
                v['venue']['location']['lat'], 
                v['venue']['location']['lng'],  
                v['venue']['categories'][0]['name'],
                ','.join(v['venue']['location']['formattedAddress'])) for v in searchResults])

In [168]:
categoryId = Food_LocationId

#multiple location id
url = 'https://api.foursquare.com/v2/venues/explore?&client_id={}&client_secret={}&v={}&ll={},{}&categoryId={}&radius={}&limit={}'.format(
    CLIENT_ID, 
    CLIENT_SECRET, 
    VERSION,
    neighborhood_latitude, 
    neighborhood_longitude, 
    categoryId,
    radius, 
    LIMIT)

results = requests.get(url).json()

searchResults = results['response']['groups'][0]['items']

venues_list = []
venues_list.append([(
                v['venue']['id'],
                v['venue']['name'], 
                v['venue']['location']['lat'], 
                v['venue']['location']['lng'],  
                v['venue']['categories'][0]['name'],
                ','.join(v['venue']['location']['formattedAddress']),
                v['venue']['photos']['count']) for v in searchResults])

nearby_venues = pd.DataFrame([item for venue_list in venues_list for item in venue_list])
nearby_venues.columns = [
              'Venue Id',
              'Venue Name', 
              'Venue Latitude', 
              'Venue Longitude', 
              'Venue Category',
              'Venue Address',
                'Number of Photo']
nearby_venues

,Venue Id,Venue Name,Venue Latitude,Venue Longitude,Venue Category,Venue Address,Number of Photo
0,57ff1a38d67c5a46abe64bb1,人情咖啡馆,3.210815,101.673668,Chinese Restaurant,"Jalan 5/18 (Batu 5, Jalan Ipoh),Kuala Lumpur,M...",0
1,582c77bab39f962e281b9645,源記海鮮飯店,3.209643,101.662708,Restaurant,Malaysia,0
2,525ba8cc11d2bc4d11c6cb01,Nasi campur Warung Kampung Stesyen,3.211272,101.673915,Malay Restaurant,Malaysia,0
3,4e9d0af477c815a0f59f54cf,Selera Kampung Mawar Tomyam,3.201177,101.669628,Malay Restaurant,"Jalan ipoh,Kuala Lumpur, Federal Territory of ...",0
4,4e59ea137d8b966a15d01e7a,Norway Salmon Fish Head Noodle,3.203677,101.667586,Noodle House,"No.7, Jalan Jambu Hadapan, (Dewan Sri Selima),...",0
...,...,...,...,...,...,...,...
95,598e963b123a190a439cee05,Posh Coffee Roastery,3.209173,101.651758,Café,"UNIO Residence Show Gallery (Lot. 9878, Batu 6...",0
96,58f1a01afe374030a19b0de1,增江酿豆腐 | Restoran Jinjang Yong Tau Fu,3.212936,101.659023,Chinese Restaurant,"2358 (Jalan Tebing Timor),52000 Kepong, KL,Mal...",0
97,596af244ad17897fe0e67ba8,Chef Tam Cantonese Cuisine,3.219476,101.671296,Cantonese Restaurant,"Lot 1-30, No.972, Eco Sky, (Batu 6 1/2, Jalan ...",0
98,589a91677220e630f25d5170,順興肉骨茶,3.208481,101.657939,Fujian Restaurant,Malaysia,0
99,591ff0a035f9836382e1271f,De Veyron Cafe,3.219909,101.670525,Café,"Kuala Lumpur, Kuala Lumpur,Malaysia",0

In [227]:
#950 calls per day

#venue ids
idNo1 = '4c5ba4192815c9281618b067'
idNo2 = '5004f1d0e4b0b7eb526730d0'
idNo3 = '4d25d24b38d0236ac8f6eeb6'

venues_list = []
for VENUE_ID in [idNo1, idNo2, idNo3]:

    #multiple location id
    url = 'https://api.foursquare.com/v2/venues/{}?v={}&client_id={}&client_secret={}'.format(
        VENUE_ID,
        VERSION,
        CLIENT_ID, 
        CLIENT_SECRET,)

    results = requests.get(url).json()
    
    #get one for checking
    searchResults = results['response']
    
    v = results['response']
    
    tempList = [
                v['venue']['id'],
                v['venue']['name'], 
                v['venue']['location']['lat'], 
                v['venue']['location']['lng'],  
                v['venue']['categories'][0]['name'],
                ','.join(v['venue']['location']['formattedAddress']),
                v['venue']['photos']['count'],
                v['venue']['likes']['count'],
                ]
    
    #check if col exists for direct extract
    colList = ['dislike', 'rating', 'seasonalHours']
    for col in colList:
        if col in v['venue'].keys():
            tempList.append(v['venue'][col])
        else:
            tempList.append('')
    
    #review
    if len(v['venue']['tips']['groups'])>0:
        reviewInfo = v['venue']['tips']['groups'][0]['items']
        reviewList = [i['text'] for i in reviewInfo]
        tempList += ['|'.join(reviewList)]
    else:
        tempList.append('')
        
    #price
    tempList.append(v['venue']['price']['message'])
    
    venues_list.append(tempList)

dfVenues = pd.DataFrame(venues_list)
dfVenues.columns = [
              'Venue Id',
              'Venue Name', 
              'Venue Latitude', 
              'Venue Longitude', 
              'Venue Category',
              'Venue Address',
              'Number of Photo',
              'Number of Likes',
              'Number of Dislikes',
              'Rating',
               'Seasonal Hours',
              'Review',
              'Price']
#process dislikes
dfVenues['Number of Dislikes'] = dfVenues['Number of Dislikes'].map(lambda x:0 if x == False else x)

#source
# dfVenues['Source'] = 'FourSquareAPI'

dfVenues

,Venue Id,Venue Name,Venue Latitude,Venue Longitude,Venue Category,Venue Address,Number of Photo,Number of Likes,Number of Dislikes,Rating,Seasonal Hours,Review,Price
0,4c5ba4192815c9281618b067,Restoran Kari Kepala Ikan E&O,3.211959,101.670284,Seafood Restaurant,"Jalan Sibu 8,68100 Kuala Lumpur, Kuala Lumpur,...",209,85,0,6.8,[],The best fish head curry ... highly recommende...,Expensive
1,5004f1d0e4b0b7eb526730d0,SUBWAY,3.204798,101.667728,Sandwich Place,"Brem Mall (G-06),52000 Kuala Lumpur, Kuala Lum...",67,18,0,7.0,[],Always awesome... Wat can I say more because i...,Cheap
2,4d25d24b38d0236ac8f6eeb6,Bull Daddy Steak House,3.210155,101.672824,Steakhouse,"2, Jalan 4/18A,51200 Kuala Lumpur, Kuala Lumpu...",73,48,0,6.3,[],Garlic chicken not bad !,Very Expensive

In [169]:
url = 'https://api.foursquare.com/v2/venues/{}?v={}&client_id={}&client_secret={}'.format(
    VENUE_ID,
    VERSION,
    CLIENT_ID, 
    CLIENT_SECRET,)

results = requests.get(url).json()
results

{'meta': {'code': 429,
  'errorType': 'quota_exceeded',
  'errorDetail': 'Quota exceeded',
  'requestId': '612d16a0d67cce2ae2ecab4f'},
 'response': {}}

In [171]:
dfVenues['Source'] = 'FourSquareAPI'
dfVenues

,Venue Id,Venue Name,Venue Latitude,Venue Longitude,Venue Category,Venue Address,Number of Photo,Number of Likes,Number of Dislikes,Rating,Seasonal Hours,Review,Price,Source
0,4c5ba4192815c9281618b067,Restoran Kari Kepala Ikan E&O,3.211959,101.670284,Seafood Restaurant,"Jalan Sibu 8,68100 Kuala Lumpur, Kuala Lumpur,...",209,85,0,6.8,[],The best fish head curry ... highly recommende...,Expensive,FourSquareAPI
1,5004f1d0e4b0b7eb526730d0,SUBWAY,3.204798,101.667728,Sandwich Place,"Brem Mall (G-06),52000 Kuala Lumpur, Kuala Lum...",67,18,0,7.0,[],Always awesome... Wat can I say more because i...,Cheap,FourSquareAPI
2,4d25d24b38d0236ac8f6eeb6,Bull Daddy Steak House,3.210155,101.672824,Steakhouse,"2, Jalan 4/18A,51200 Kuala Lumpur, Kuala Lumpu...",73,48,0,6.1,[],Garlic chicken not bad !,Very Expensive,FourSquareAPI

In [172]:
filename = "fourSquareExample.csv"
dfVenues.to_csv(filename, index = False)

### Google Map API

In [186]:
#create api key: https://console.cloud.google.com/google/maps-apis/credentials?project=proud-effect-324517
#enable geocoding API: https://console.cloud.google.com/apis/dashboard
link = 'https://maps.googleapis.com/maps/api/geocode/json?address='
address = 'lakeville residence' + ',Malaysia'
APIkey = 'AIzaSyBd0JsoMFk8noJ2xdqkhUWoWzbvxcZj12U'

response = requests.get(link + address + '&key=' + APIkey)
dataDict = response.json()

corDict = dataDict['results'][0]['geometry']['location']
lat = corDict['lat']
lng = corDict['lng']
lat, lng

(3.2087134, 101.6689777)

In [192]:
#place type:https://developers.google.com/maps/documentation/places/web-service/supported_types
placeType = "restaurant"
link = "https://maps.googleapis.com/maps/api/place/nearbysearch/json?"\
        + "location=%s,%s&radius=2000&type=%s"%(lat, lng, placeType)
APIkey = 'AIzaSyBd0JsoMFk8noJ2xdqkhUWoWzbvxcZj12U'

response = requests.get(link + '&key=' + APIkey)

placesDict = response.json()

In [219]:
placesDict['results'][1]

{'business_status': 'OPERATIONAL',
 'geometry': {'location': {'lat': 3.200582599999999, 'lng': 101.6777206},
  'viewport': {'northeast': {'lat': 3.201897280291501,
    'lng': 101.6790074802915},
   'southwest': {'lat': 3.199199319708498, 'lng': 101.6763095197085}}},
 'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png',
 'icon_background_color': '#7B9EB0',
 'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/generic_pinlet',
 'name': 'Big Onion Food Caterer',
 'opening_hours': {'open_now': False},
 'photos': [{'height': 3648,
   'html_attributions': ['<a href="https://maps.google.com/maps/contrib/101455210651939895825">Big Onion Food Caterer</a>'],
   'photo_reference': 'Aap_uED69JOuPwuTY4xNRJRV_2sXqgeJNqIX6n3HndtcH1CTxt1eYzB3pdakhJHsGQgcZpaaeOPTVKa0BB53mBm5k2m3oW0CaxnJbM4prYNZOUWR8KCU7LUQtlFJjAfiXn2uZB0FDSH2GW00abyD2xZcaTIoERVR0Xy9mCaCRHAjlX6Z_Nc6',
   'width': 5472}],
 'place_id': 'ChIJy0bhv3JIzDERfKq9bCpFqx4',
 'plus_code': {'compound_code': '6M2H+63 Kuala Lumpur, Federal Territory of Kuala Lumpur, Malaysia',
  'global_code': '6PM36M2H+63'},
 'rating': 4.1,
 'reference': 'ChIJy0bhv3JIzDERfKq9bCpFqx4',
 'scope': 'GOOGLE',
 'types': ['restaurant',
  'food',
  'point_of_interest',
  'store',
  'establishment'],
 'user_ratings_total': 43,
 'vicinity': '1/2, LOT 430, BATU 2, Jalan Sultan Azlan Shah, Kuala Lumpur'}

In [213]:
placesDict['results'][10]['types']

['restaurant', 'food', 'point_of_interest', 'establishment']

In [ ]:
[
              'Venue Id',
              'Venue Name', 
              'Venue Latitude', 
              'Venue Longitude', 
              'Venue Category',
              'Venue Address',
              'Number of Photo',
              'Number of Likes',
              'Number of Dislikes',
              'Rating',
               'Seasonal Hours',
              'Review',
              'Price']

In [220]:
#example:
venues_list2 = []
for result in placesDict['results']:
    tempList = [
                result['place_id'],
                result['name'],
                result['geometry']['location']['lat'],
                result['geometry']['location']['lng'],
                ]
    
    for col in ['rating', 'user_ratings_total', 'vicinity']:
        if col in result.keys():
            tempList.append(result[col])
        else:
            tempList.append('')
    
    #category
    categoryInfo = result['types']
    categoryInfo = ','.join([i for i in categoryInfo if i not in ['point_of_interest', 'establishment']])
    tempList.append(categoryInfo)
    
    venues_list2.append(tempList)

In [224]:
dfVenues2 = pd.DataFrame(venues_list2)
dfVenues2.columns = [
              'Venue Id',
              'Venue Name', 
              'Venue Latitude', 
              'Venue Longitude',
               'Rating',
                'Total Rating',
                'Vicinity',
              'Venue Category',]
dfVenues2['Source'] = "GoogleMap API"
dfVenues2.head()

,Venue Id,Venue Name,Venue Latitude,Venue Longitude,Rating,Total Rating,Vicinity,Venue Category,Source
0,ChIJlSTt2sVHzDERfFT3Iz4KW6E,Batu Village Corner,3.204934,101.675040,3.8,8,"42, Jalan Kampung Batu, Kampung Batu, Kuala Lu...","restaurant,food",GoogleMap API
1,ChIJy0bhv3JIzDERfKq9bCpFqx4,Big Onion Food Caterer,3.200583,101.677721,4.1,43,"1/2, LOT 430, BATU 2, Jalan Sultan Azlan Shah,...","restaurant,food,store",GoogleMap API
2,ChIJa0Ovn85HzDERYmDZ2anGvc0,Marrybrown Brem Mall,3.204622,101.667135,3.5,199,"Brem Mall, Kepong 11, GF, Jalan Besar Kepong, ...","restaurant,food",GoogleMap API
3,ChIJEwiZ3q9HzDER6lIT56Nd7iU,Rasamas,3.204307,101.675730,4.5,2,Malaysia,"restaurant,food",GoogleMap API
4,ChIJA6K1m85HzDERCqrYQ48fEhU,Secret Recipe Brem Mall,3.204779,101.667497,3.8,160,"G-09 ;Ground Floor, Brem Mall, Jalan Kepong, J...","restaurant,food",GoogleMap API

In [225]:
filename = "googleMapExample.csv"
dfVenues2.to_csv(filename, index = False)

Hi, it is really interesting to extract such information from both API. With at least 5 years of exp using Python and some in web scraping as Data Scientist, I believe I can be helpful in this problem. Please refer to the attached csv files that i have just scraped using both API and my location as examples. The examples show information we can extract from both sources and hopefully it can give you a better idea. Please give me a call to discuss further and I am looking forward to tackle this problem together. Thanks.